/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsCalculadora;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Calculadora c = new Calculadora();

        System.out.println(new App().getGreeting());
        System.out.println("CALCULADORA");
        System.out.println("===========");
        System.out.println("2+3="+ c.suma(2, 3));
        System.out.println("2*3=" + c.multiplica(2, 3));
        System.out.println("3.4 * 4.5=" + c.multiplica(3.4,4.5));
    }
}
